# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d8c57932e9c904d053ab852ca4b814e0044ad001b4a28c74c3073e34c8a4f2276796afa9469d7fa317ce1430582be9bc1fa0b58e7444a8319c45858373dc8c0

test:
  secret_key_base: ecf8fad487268d77bef2792de94d2a7540c238aee827e437fe9aa9a769c31688fb8b0e1847145476ebddebaeb3ff207f2ababee6ffeac42cf0eef877f06c1c72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
